name: PR Agent

on:
  workflow_call:
    secrets:
      GEMINI_API_KEY:
        required: true

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write
      contents: write
      checks: write

    name: Run PR Agent on every PR

    steps:
      - name: PR Agent action step
        uses: the-pr-agent/pr-agent@main
        env:
          # GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Google AI Studio
          GOOGLE_AI_STUDIO__GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

          # PR Agent configuration
          config.model: "gemini/gemini-3.1-flash-lite-preview"

          # Description settings
          pr_description.publish_description_as_comment: "true"
          pr_description.publish_description_as_comment_persistent: "false"
          pr_description.add_original_user_description: "false"
          pr_description.enable_pr_type: "false"
          pr_description.enable_pr_diagram: "false"

          # Suggestion settings
          pr_code_suggestions.persistent_comment: "false"
          pr_code_suggestions.commitable_code_suggestions: "true"

          # App settings
          github_action_config.auto_review: "false"
          github_action_config.auto_describe: "true"
          github_action_config.auto_improve: "true"
